const mongoose = require('mongoose');

const fixtureSchema = new mongoose.Schema({
  type: String,
  match_id: String,
  name: String,
  date: Date,
  round: String,
  full_round: String,
  ground_name: String,
  ground_latitude: { type: Number, default: null },
  ground_longitude: { type: Number, default: null },
  ground_address: { type: String, default: null },
  field_name: String,
  is_historic_field: Boolean,
  home_team_name: String,
  home_logo: String,
  away_team_name: String,
  away_logo: String,
  competition_name: String,
  league_name: String,
  status: { type: String, default: 'pending' },
  bye_flag: Boolean,
  is_unstructured: Boolean,
  league_result_access: String,
  home_score: { type: Number, default: null },
  home_score_extra: { type: Number, default: null },
  home_score_penalty: { type: Number, default: null },
  home_score_half: { type: Number, default: null },
  home_score_extra_half: { type: Number, default: null },
  away_score: { type: Number, default: null },
  away_score_extra: { type: Number, default: null },
  away_score_penalty: { type: Number, default: null },
  away_score_half: { type: Number, default: null },
  away_score_extra_half: { type: Number, default: null },
  allocated_center_referee: Boolean,
  allocated_assistant_referee_1: Boolean,
  allocated_assistant_referee_2: Boolean,
  allocated_fourth_official: Boolean,
  allocated_game_leader: Boolean,
  referee_count: { type: Number, default: 0 },
  enable_referees_allocated: Boolean,
  match_hash_id: String, // Match hash for future reference
  forfeit_team_hash_id: { type: String, default: null },
  home_team_hash_id: String,
  away_team_hash_id: String,
});

module.exports = mongoose.model('Fixture', fixtureSchema);
